---
title: "Sea Ice Redesign"
author: "Wylie Hampson"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(ggrepel)
```

# Sea Ice Redesign

In this Assignment I will attempt to improve upon the "Arctic Death Spiral" graphic that we explored in my EDS 240 class.

#### Import the data.

```{r}
sea_ice <- read.csv(here("data", "PIOMAS.vol.daily.1979.2021.Current.v2.1.csv")) %>% 
  clean_names() %>% 
  mutate(date = as_date((x_day - 1), origin = paste0(year, "-01-01"))) %>% # create a date for each day
  mutate(month = month(date), year = year(date))
```

#### Start with a simple plot.

```{r}
sea_ice_by_month <- sea_ice %>% 
  mutate(month = (month(date, label = TRUE, abbr = FALSE)),
         label = month(date, label = TRUE, abbr = FALSE)) %>% 
  group_by(year, month) %>% 
  summarize(avg_vol = mean(vol), date, label)

by_month_plot <- ggplot(sea_ice_by_month, aes(date, avg_vol)) +
  geom_line(aes(group = month, color = month))

by_month_plot
```

```{r}
label_df <- sea_ice_by_month %>% 
  mutate(label = month) %>%
  group_by(month) %>% 
  summarize(date = max(date), label, avg_vol) %>% 
  mutate(year = year(date))
```


#### Add a line for mean ice-vol for the years.

```{r, fig.width = 6, fig.height = 3}
sea_ice_mean <- sea_ice %>% 
  mutate(label = ifelse(year == 2021, "Yearly Average", NA)) %>% 
  group_by(year) %>% 
  summarize(avg_vol = mean(vol), date, label) %>% 
  filter(str_detect(date, "06-01", negate = FALSE))

months <- c("January", "February", "March", "April", "May","June", "July",
            "August", "September", "October","November", "December")

colors_scheme <- c("#b63434", "#b63434", "#601ea1", "#248df0", "#0cb3a7", "#138261",
                    "#35e077", "#2de109", "#abb337", "#d4bc16", "#9ad0a7", "#4e7256")

colors_scheme_colorblind <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                             "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

final_plot <- ggplot(sea_ice_by_month, aes(date, avg_vol)) +
  geom_line(aes(x = date, group = month, color = label)) +
  geom_line(data = sea_ice_mean,
            size = 2) +
  geom_text(data = sea_ice_by_month %>% 
               group_by(month) %>% 
               filter(date == max(date)),
            aes(label = label),
            check_overlap = FALSE,
            nudge_x = 600,
            size = 3) +
  geom_text(data = sea_ice_mean %>% filter(date == max(date)),
            aes(label = label),
            size = 3,
            nudge_x = 700,
            nudge_y = 0.4) +
  labs(x = "Year",
       y = "Sea Ice Volume (10^3 km^3)",
       title = "PIOMAS Arctic Sea Ice Volume") +
  scale_color_manual(labels = months,
                     values = colors_scheme_colorblind,
                     name = "Month")

final_plot

```

#### Save the plot

```{r}
final_plot %>% ggsave(filename = "sea_ice_plot", device = jpeg, width = 12, height = 5)
```








